// SOBRE BUTTONS
// ONCLICK = CUANDO HAGO CLICK
// ONMOUSEOVER : CUANDO PASO EL CURSOR POR ENCIMA DEL OBJETO
// ONMOUSEOUT : CUANDO SACAMOS EL CURSOR DEL BOTON
// ONMOUSEMOVE : CUANDO MOVEMOS EL CURSOR

//SOBRE INPUTS
// ONCHANGE : CUANDO SE CAMBIA EL VALOR DENTRO DEL INPUT 
// ONBLUR : DEJAMOS DE HACER FOCO EN EL INPUT HAYAMOS HECHO UN CAMBIO O NO
 ONFOCUS : CUANDO HACES FOCO EN EL INPUT
 ONKEYPRESS : CUANDO PRESIONAS UNA  TECLA EN EL INPUT(ANTES DE QUE APAREZCA LA LETRA)
 ONKEYUP : DEJASTE DE PRESIONAR UNA LETRA (CUANDO VEO EL CARACTER SE ACTIVA)